import assert from 'node:assert/strict';
import { INITIAL_STATE, referenceTrajectory } from './physics.mjs';
import { coachHint, innerRearWheelKey, nearestReferencePose, predictedSweepSamples, predictLineRisk, referenceDeviation } from './coach.mjs';

assert.equal(innerRearWheelKey(0.3), 'rl');
assert.equal(innerRearWheelKey(-0.3), 'rr');
assert.equal(innerRearWheelKey(0), null);
const sweep=predictedSweepSamples({...INITIAL_STATE,gear:'R',steer:.2},{distance:2,samples:20});assert.equal(sweep.length,20);assert.equal(sweep[0].polygon.length,4);assert.ok(Number.isFinite(sweep.at(-1).pose.rearX));
const farSafe={...INITIAL_STATE,rearX:8,rearZ:8,yaw:0,gear:'D',speed:0,steer:0};const safeRisk=predictLineRisk(farSafe,{distance:1,samples:20});assert.equal(safeRisk.willTouch,false);assert.equal(safeRisk.distanceAhead,null);assert.deepEqual(safeRisk.hitLines,[]);assert.equal(coachHint(farSafe,{distance:1,samples:20}).code,'path-clear');
const nearBackLine={...INITIAL_STATE,rearX:0,rearZ:-4.25,yaw:Math.PI,gear:'R',speed:0,steer:0};const backRisk=predictLineRisk(nearBackLine,{distance:1,samples:100});assert.equal(backRisk.willTouch,true);assert.ok(backRisk.distanceAhead>0&&backRisk.distanceAhead<.5);assert.deepEqual(backRisk.hitLines,['back']);assert.match(coachHint(nearBackLine,{distance:1,samples:100}).text,/后侧库线/);
// First-contact distance should stay stable even when the coarse prediction sample count changes.
const coarseRisk=predictLineRisk(nearBackLine,{distance:1,samples:5});const fineRisk=predictLineRisk(nearBackLine,{distance:1,samples:100});assert.ok(Math.abs(coarseRisk.distanceAhead-fineRisk.distanceAhead)<.003,`coarse/fine risk distance drifted: ${coarseRisk.distanceAhead} vs ${fineRisk.distanceAhead}`);assert.deepEqual(coarseRisk.hitLines,['back']);
const touchingLeft={...INITIAL_STATE,rearX:-1.25,rearZ:-2.5,yaw:Math.PI,gear:'D',speed:0,steer:0};const currentRisk=predictLineRisk(touchingLeft,{distance:.2,samples:10});assert.equal(currentRisk.alreadyTouching,true);assert.ok(currentRisk.hitLines.includes('left'));const currentHint=coachHint(touchingLeft,{distance:.2,samples:10});assert.equal(currentHint.code,'line-touch-now');assert.match(currentHint.text,/左侧库线/);
const turningHint=coachHint({...farSafe,steer:.2},{distance:.2,samples:10});assert.equal(turningHint.code,'watch-inner-rear-wheel');assert.match(turningHint.text,/左后轮/);
const ref=referenceTrajectory(),midIndex=Math.floor(ref.length*.55),mid=ref[midIndex],nearest=nearestReferencePose(mid,ref);assert.equal(nearest.index,midIndex);assert.ok(nearest.distance<1e-10);const c=Math.cos(mid.yaw),si=Math.sin(mid.yaw);const shiftedRight={...mid,rearX:mid.rearX+.5*c,rearZ:mid.rearZ-.5*si,speed:0,gear:'D',steer:0};const rightDeviation=referenceDeviation(shiftedRight,ref);assert.ok(rightDeviation.lateral>.45);assert.equal(coachHint(shiftedRight,{distance:.1,samples:5}).code,'reference-lateral-deviation');const headingOff={...mid,yaw:mid.yaw+10*Math.PI/180,speed:0,gear:'D',steer:0};assert.ok(Math.abs(referenceDeviation(headingOff,ref).headingErrorDeg-10)<1e-8);assert.equal(coachHint(headingOff,{distance:.1,samples:5}).code,'reference-heading-deviation');
console.log('coach-tests: all assertions passed');
