import { resolveReplayStep } from './replay-runtime.mjs';

export const VEHICLE = Object.freeze({length:4.46,width:1.78,wheelbase:2.62,trackWidth:1.52,frontOverhang:.93,rearOverhang:.91,wheelRadius:.31,wheelWidth:.19,maxRoadWheelAngle:.56,steeringWheelMaxDeg:540,roadWheelRate:.82,forwardSpeed:1.20,reverseSpeed:1.05,acceleration:1.65,coastBrake:2.20,directionChangeBrake:3.00});
export const CONTROL_BINDINGS=Object.freeze({KeyW:'forward',ArrowUp:'forward',KeyS:'reverse',ArrowDown:'reverse',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'});
export const COURSE=Object.freeze({bayWidth:2.50,bayDepth:5.20,openingZ:-.20,backZ:-5.40,lineWidth:.08,centerX:0,centerZ:-2.80});
export const INITIAL_STATE=Object.freeze({rearX:4.80,rearZ:3.20,yaw:-Math.PI/2,speed:0,steer:0,gear:'R'});
export const PARKING_STOP_SPEED=0.02;
export const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
const finite=(v,f=0)=>Number.isFinite(v)?v:f;
/** Constant-time angle normalization. Non-finite angles degrade safely instead of hanging in a while loop. */
export function normalizeAngle(a){if(!Number.isFinite(a))return 0;const tau=Math.PI*2;let v=((a+Math.PI)%tau+tau)%tau-Math.PI;if(v<=-Math.PI)v+=tau;return v}
export function cloneState(s=INITIAL_STATE){return {...s}}
export function localToWorld(lx,lz,s){const yaw=normalizeAngle(s?.yaw),c=Math.cos(yaw),si=Math.sin(yaw),rearX=finite(s?.rearX),rearZ=finite(s?.rearZ);return{x:rearX+finite(lx)*c+finite(lz)*si,z:rearZ-finite(lx)*si+finite(lz)*c}}
export function frontDirection(s){const yaw=normalizeAngle(s?.yaw);return{x:-Math.sin(yaw),z:-Math.cos(yaw)}}
export function integratePose(s,distance,steer=s?.steer){const safeSteer=clamp(finite(steer),-VEHICLE.maxRoadWheelAngle,VEHICLE.maxRoadWheelAngle),base={...s,rearX:finite(s?.rearX),rearZ:finite(s?.rearZ),yaw:normalizeAngle(s?.yaw),steer:safeSteer},safeDistance=finite(distance);if(Math.abs(safeDistance)<1e-12)return base;const k=Math.tan(safeSteer)/VEHICLE.wheelbase;if(Math.abs(k)<1e-10)return{...base,rearX:base.rearX-Math.sin(base.yaw)*safeDistance,rearZ:base.rearZ-Math.cos(base.yaw)*safeDistance};const yaw2=base.yaw+k*safeDistance;return{...base,rearX:base.rearX+(Math.cos(yaw2)-Math.cos(base.yaw))/k,rearZ:base.rearZ+(Math.sin(base.yaw)-Math.sin(yaw2))/k,yaw:normalizeAngle(yaw2)}}
/** Integrate a bounded constant-acceleration velocity step exactly, including time spent at target speed after reaching it. */
export function velocityStep(oldSpeed,targetSpeed,rate,dt){const old=finite(oldSpeed),target=finite(targetSpeed),safeRate=Math.max(0,finite(rate)),safeDt=Math.max(0,finite(dt));if(safeDt===0||safeRate===0)return{speed:old,distance:old*safeDt,reached:old===target};const delta=target-old,maxChange=safeRate*safeDt;if(Math.abs(delta)>maxChange){const speed=old+Math.sign(delta)*maxChange;return{speed,distance:.5*(old+speed)*safeDt,reached:false}}const reachTime=Math.abs(delta)/safeRate,remaining=Math.max(0,safeDt-reachTime),distance=.5*(old+target)*reachTime+target*remaining;return{speed:target,distance,reached:true}}
export function stepVehicle(s,dt,controls={}){const replay=resolveReplayStep(s);if(replay.handled)return replay.state;const safeDt=clamp(finite(dt),0,.25),next={...s,rearX:finite(s?.rearX),rearZ:finite(s?.rearZ),yaw:normalizeAngle(s?.yaw),speed:finite(s?.speed),steer:clamp(finite(s?.steer),-VEHICLE.maxRoadWheelAngle,VEHICLE.maxRoadWheelAngle)},left=!!controls.left,right=!!controls.right,reverse=!!controls.reverse,forward=!!controls.forward,steerStart=next.steer;if(left!==right)next.steer=clamp(next.steer+(left?1:-1)*VEHICLE.roadWheelRate*safeDt,-VEHICLE.maxRoadWheelAngle,VEHICLE.maxRoadWheelAngle);if(controls.centerSteering)next.steer=0;let targetSpeed=0;if(reverse!==forward){if(reverse){targetSpeed=-VEHICLE.reverseSpeed;next.gear='R'}else{targetSpeed=VEHICLE.forwardSpeed;next.gear='D'}}const oldSpeed=next.speed,changingDirection=targetSpeed!==0&&oldSpeed!==0&&Math.sign(targetSpeed)!==Math.sign(oldSpeed),effectiveTarget=changingDirection?0:targetSpeed,rate=changingDirection?VEHICLE.directionChangeBrake:(targetSpeed===0?VEHICLE.coastBrake:VEHICLE.acceleration),motion=velocityStep(oldSpeed,effectiveTarget,rate,safeDt);next.speed=motion.speed;if(Math.abs(next.speed)<1e-4&&targetSpeed===0)next.speed=0;/* Steering changes continuously during the step. Using the midpoint angle avoids applying the final wheel angle retroactively to the whole travelled distance, which otherwise over-turns during low-FPS/large-dt input ramps. */const motionSteer=controls.centerSteering?0:.5*(steerStart+next.steer),posed=integratePose(next,motion.distance,motionSteer);next.rearX=posed.rearX;next.rearZ=posed.rearZ;next.yaw=posed.yaw;return next}
export function steeringWheelDegrees(a){return clamp(finite(a),-VEHICLE.maxRoadWheelAngle,VEHICLE.maxRoadWheelAngle)/VEHICLE.maxRoadWheelAngle*VEHICLE.steeringWheelMaxDeg}
export function ackermannAngles(steer){const safeSteer=clamp(finite(steer),-VEHICLE.maxRoadWheelAngle,VEHICLE.maxRoadWheelAngle);if(Math.abs(safeSteer)<1e-8)return{left:0,right:0};const absR=VEHICLE.wheelbase/Math.abs(Math.tan(safeSteer)),inner=Math.atan(VEHICLE.wheelbase/Math.max(.05,absR-VEHICLE.trackWidth/2)),outer=Math.atan(VEHICLE.wheelbase/(absR+VEHICLE.trackWidth/2));return safeSteer>0?{left:inner,right:outer}:{left:-outer,right:-inner}}
export function wheelPoints(s){const h=VEHICLE.trackWidth/2;return{rl:localToWorld(-h,0,s),rr:localToWorld(h,0,s),fl:localToWorld(-h,-VEHICLE.wheelbase,s),fr:localToWorld(h,-VEHICLE.wheelbase,s)}}
export function bodyPolygon(s){const hw=VEHICLE.width/2,fz=-(VEHICLE.wheelbase+VEHICLE.frontOverhang),rz=VEHICLE.rearOverhang;return[localToWorld(-hw,fz,s),localToWorld(hw,fz,s),localToWorld(hw,rz,s),localToWorld(-hw,rz,s)]}
export function rectPolygon(cx,cz,width,depth){const hw=width/2,hd=depth/2;return[{x:cx-hw,z:cz-hd},{x:cx+hw,z:cz-hd},{x:cx+hw,z:cz+hd},{x:cx-hw,z:cz+hd}]}
function axesFor(poly){const axes=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ex=b.x-a.x,ez=b.z-a.z,len=Math.hypot(ex,ez)||1;axes.push({x:-ez/len,z:ex/len})}return axes}
function projection(poly,axis){let min=Infinity,max=-Infinity;for(const p of poly){const v=p.x*axis.x+p.z*axis.z;min=Math.min(min,v);max=Math.max(max,v)}return{min,max}}
export function polygonsOverlapSAT(a,b,epsilon=1e-9){for(const axis of[...axesFor(a),...axesFor(b)]){const pa=projection(a,axis),pb=projection(b,axis);if(pa.max<pb.min-epsilon||pb.max<pa.min-epsilon)return false}return true}
export function courseLinePolygons(){const c=COURSE,sideCenterZ=(c.openingZ+c.backZ)/2,sideDepth=c.openingZ-c.backZ;return[rectPolygon(-c.bayWidth/2,sideCenterZ,c.lineWidth,sideDepth),rectPolygon(c.bayWidth/2,sideCenterZ,c.lineWidth,sideDepth),rectPolygon(0,c.backZ,c.bayWidth+c.lineWidth,c.lineWidth)]}
const LINE_POLYS=courseLinePolygons();
export const COURSE_LINE_NAMES=Object.freeze(['left','right','back']);
/** Detailed collision result for coaching/replay highlighting. */
export function lineCollisionDetails(s){const car=bodyPolygon(s),hits=[];for(let i=0;i<LINE_POLYS.length;i++)if(polygonsOverlapSAT(car,LINE_POLYS[i]))hits.push({index:i,name:COURSE_LINE_NAMES[i],polygon:LINE_POLYS[i].map(p=>({...p}))});return{touching:hits.length>0,hits}}
export function lineViolation(s){return lineCollisionDetails(s).touching}
/** Signed distance from the car body to each parking-bay line's inner edge. Positive means clear, 0 means tangent, negative means crossing the line. */
export function bayClearances(s){const poly=bodyPolygon(s),xs=poly.map(p=>p.x),zs=poly.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),leftEdge=-COURSE.bayWidth/2+COURSE.lineWidth/2,rightEdge=COURSE.bayWidth/2-COURSE.lineWidth/2,backEdge=COURSE.backZ+COURSE.lineWidth/2,left=minX-leftEdge,right=rightEdge-maxX,back=minZ-backEdge;return{left,right,back,minSide:Math.min(left,right),sideImbalance:left-right,min:Math.min(left,right,back)}}
export function isFullyInsideBay(s,margin=0){const l=-COURSE.bayWidth/2+COURSE.lineWidth/2+margin,r=COURSE.bayWidth/2-COURSE.lineWidth/2-margin,f=COURSE.openingZ-COURSE.lineWidth/2-margin,b=COURSE.backZ+COURSE.lineWidth/2+margin;return bodyPolygon(s).every(p=>p.x>l&&p.x<r&&p.z<f&&p.z>b)}
export function headingErrorToBay(s){return Math.abs(normalizeAngle(s?.yaw-Math.PI))}
/** Completion requires the vehicle to be essentially stopped, not merely creeping through a valid pose. */
export function parkingSuccess(s){return isFullyInsideBay(s,.015)&&headingErrorToBay(s)<5*Math.PI/180&&Math.abs(finite(s?.speed))<=PARKING_STOP_SPEED}
/** Prediction follows actual residual motion until the car is effectively stopped; gear is only a fallback at rest. */
export function predictionDirection(s){const speed=finite(s?.speed);if(Math.abs(speed)>1e-4)return Math.sign(speed);return s?.gear==='D'?1:-1}
/** Deterministic trajectory prediction with bounded, finite inputs. */
export function predictStates(s,{distance=4.2,samples=80}={}){const safeDistance=Number.isFinite(distance)?Math.max(0,distance):0;const safeSamples=Number.isFinite(samples)?Math.max(1,Math.min(2000,Math.floor(samples))):80;const dir=predictionDirection(s),stepDistance=dir*safeDistance/safeSamples,states=[];let sim=integratePose(s,0,s?.steer);for(let i=0;i<safeSamples;i++){sim=integratePose(sim,stepDistance,sim.steer);states.push(sim)}return states}
export function referenceTrajectory(){let s=cloneState(INITIAL_STATE);const states=[{...s}],radius=INITIAL_STATE.rearX-COURSE.centerX,steer=Math.atan(VEHICLE.wheelbase/radius);s.steer=steer;const k=Math.tan(steer)/VEHICLE.wheelbase,arcDistance=(-Math.PI/2)/k;for(let i=0;i<150;i++){s=integratePose(s,arcDistance/150,steer);s.steer=steer;states.push({...s})}s.steer=0;const straightDistance=-4.30-s.rearZ;for(let i=0;i<45;i++){s=integratePose(s,straightDistance/45,0);s.steer=0;states.push({...s})}return states}