import assert from 'node:assert/strict';
import {
  VEHICLE, COURSE, CONTROL_BINDINGS, INITIAL_STATE, PARKING_STOP_SPEED, cloneState, localToWorld, frontDirection,
  normalizeAngle, integratePose, stepVehicle, velocityStep, ackermannAngles, bodyPolygon, lineViolation,
  isFullyInsideBay, headingErrorToBay, parkingSuccess, predictionDirection, predictStates,
  referenceTrajectory, polygonsOverlapSAT, rectPolygon,
} from './physics.mjs';

const near = (a,b,e=1e-8,msg='') => assert.ok(Math.abs(a-b) <= e, `${msg} expected ${b}, got ${a}`);
const angleNear = (a,b,e=1e-8,msg='') => { let d=a-b; while(d>Math.PI)d-=2*Math.PI; while(d<=-Math.PI)d+=2*Math.PI; assert.ok(Math.abs(d)<=e, `${msg} expected ${b}, got ${a}`); };
near(normalizeAngle(0),0); near(normalizeAngle(9*Math.PI),Math.PI); near(normalizeAngle(-9*Math.PI),Math.PI); near(normalizeAngle(Infinity),0); near(normalizeAngle(-Infinity),0); near(normalizeAngle(NaN),0);
let s={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0}; near(frontDirection(s).x,0);near(frontDirection(s).z,-1);s.yaw=-Math.PI/2;near(frontDirection(s).x,1);near(frontDirection(s).z,0);
s={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,steer:0};let f=integratePose(s,5,0);near(f.rearX,0);near(f.rearZ,-5);angleNear(f.yaw,0);let r=integratePose(s,-5,0);near(r.rearX,0);near(r.rearZ,5);angleNear(r.yaw,0);
const corruptedPose=integratePose({...s,rearX:Infinity,rearZ:NaN,yaw:Infinity,steer:Infinity},Infinity,Infinity);for(const value of[corruptedPose.rearX,corruptedPose.rearZ,corruptedPose.yaw,corruptedPose.steer])assert.ok(Number.isFinite(value));assert.ok(Math.abs(corruptedPose.steer)<=VEHICLE.maxRoadWheelAngle);
const delta=.42,R=VEHICLE.wheelbase/Math.tan(delta),quarter=Math.PI/2*R;s={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,steer:delta};f=integratePose(s,quarter,delta);near(f.rearX,-R,1e-8);near(f.rearZ,-R,1e-8);angleNear(f.yaw,Math.PI/2,1e-8);
s={...INITIAL_STATE,rearX:1.2,rearZ:-.7,yaw:.37,steer:-.31};f=integratePose(s,3.7,s.steer);r=integratePose(f,-3.7,s.steer);near(r.rearX,s.rearX);near(r.rearZ,s.rearZ);angleNear(r.yaw,s.yaw);
assert.equal(CONTROL_BINDINGS.KeyW,'forward');assert.equal(CONTROL_BINDINGS.KeyS,'reverse');assert.equal(CONTROL_BINDINGS.KeyA,'left');assert.equal(CONTROL_BINDINGS.KeyD,'right');
s=cloneState(INITIAL_STATE);for(let i=0;i<120;i++)s=stepVehicle(s,1/120,{forward:true});assert.ok(s.speed>0);s={...INITIAL_STATE,gear:'R'};for(let i=0;i<120;i++)s=stepVehicle(s,1/120,{reverse:true});assert.ok(s.speed<0);
const corruptedStep=stepVehicle({...INITIAL_STATE,rearX:NaN,rearZ:Infinity,yaw:-Infinity,speed:NaN,steer:Infinity},Infinity,{forward:true,left:true});for(const value of[corruptedStep.rearX,corruptedStep.rearZ,corruptedStep.yaw,corruptedStep.speed,corruptedStep.steer])assert.ok(Number.isFinite(value));assert.ok(Math.abs(corruptedStep.steer)<=VEHICLE.maxRoadWheelAngle);assert.ok(Math.abs(corruptedStep.speed)<=VEHICLE.forwardSpeed+1e-9);
const frozenStep=stepVehicle({...INITIAL_STATE,speed:.5},NaN,{forward:true});near(frozenStep.rearX,INITIAL_STATE.rearX,1e-12);near(frozenStep.rearZ,INITIAL_STATE.rearZ,1e-12);
s={...INITIAL_STATE,steer:.4};const held=stepVehicle(s,1/60,{});near(held.steer,.4,1e-12);const centered=stepVehicle(s,1/60,{centerSteering:true});near(centered.steer,0,1e-12);
// Steering interpolation follows distance, not just wall-clock midpoint. Constant speed => 1/2; acceleration from rest => 2/3 because most distance is travelled late in the step.
const constantMotion=velocityStep(.8,.8,VEHICLE.acceleration,.25);near(constantMotion.timeFraction,.5,1e-12,'constant-speed steering fraction');
const acceleratingMotion=velocityStep(0,VEHICLE.forwardSpeed,VEHICLE.acceleration,.25);near(acceleratingMotion.timeFraction,2/3,1e-12,'acceleration steering fraction');
const rampStart={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,speed:.8,steer:0,gear:'D'};const rampDt=.25,ramped=stepVehicle(rampStart,rampDt,{forward:true,left:true}),expectedFinalSteer=VEHICLE.roadWheelRate*rampDt;near(ramped.steer,expectedFinalSteer,1e-12,'final steering state');const rampMotion=velocityStep(rampStart.speed,VEHICLE.forwardSpeed,VEHICLE.acceleration,rampDt),weightedPose=integratePose(rampStart,rampMotion.distance,expectedFinalSteer*rampMotion.timeFraction),finalAnglePose=integratePose(rampStart,rampMotion.distance,expectedFinalSteer);near(ramped.rearX,weightedPose.rearX,1e-10,'ramp weighted x');near(ramped.rearZ,weightedPose.rearZ,1e-10,'ramp weighted z');angleNear(ramped.yaw,weightedPose.yaw,1e-10,'ramp weighted yaw');assert.ok(Math.abs(ramped.yaw)<Math.abs(finalAnglePose.yaw),'weighted integration must avoid retroactive final-angle over-turning');
const fromRest={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,speed:0,steer:0,gear:'D'},fromRestTurn=stepVehicle(fromRest,.25,{forward:true,left:true}),fromRestFinalSteer=VEHICLE.roadWheelRate*.25,fromRestMotion=velocityStep(0,VEHICLE.forwardSpeed,VEHICLE.acceleration,.25),fromRestExpected=integratePose(fromRest,fromRestMotion.distance,fromRestFinalSteer*(2/3));angleNear(fromRestTurn.yaw,fromRestExpected.yaw,1e-10,'accelerating turn uses late-distance steering weight');
let a=ackermannAngles(.4);assert.ok(a.left>a.right&&a.left>0&&a.right>0);a=ackermannAngles(-.4);assert.ok(Math.abs(a.right)>Math.abs(a.left)&&a.left<0&&a.right<0);const badAckermann=ackermannAngles(Infinity);assert.ok(Number.isFinite(badAckermann.left)&&Number.isFinite(badAckermann.right));
let leftTurn={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,speed:1,steer:.3,gear:'D'};leftTurn=integratePose(leftTurn,1,leftTurn.steer);assert.ok(frontDirection(leftTurn).x<0);let rightTurn={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,speed:1,steer:-.3,gear:'D'};rightTurn=integratePose(rightTurn,1,rightTurn.steer);assert.ok(frontDirection(rightTurn).x>0);let reverseLeft={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0,speed:-1,steer:.3,gear:'R'};reverseLeft=integratePose(reverseLeft,-1,reverseLeft.steer);assert.ok(reverseLeft.yaw<0);
const rl=localToWorld(-VEHICLE.trackWidth/2,0,{...INITIAL_STATE,rearX:0,rearZ:0,yaw:0});near(rl.x,-VEHICLE.trackWidth/2);assert.ok(VEHICLE.trackWidth+VEHICLE.wheelWidth<=VEHICLE.width+1e-9);assert.equal(polygonsOverlapSAT(rectPolygon(0,0,VEHICLE.width,VEHICLE.length),rectPolygon(0,0,.08,8)),true);
s={...INITIAL_STATE,rearX:0,rearZ:-4.25,yaw:Math.PI,speed:0,steer:0};assert.equal(lineViolation(s),false);assert.equal(isFullyInsideBay(s),true);assert.ok(headingErrorToBay(s)<1e-9);assert.equal(parkingSuccess(s),true);assert.equal(parkingSuccess({...s,speed:PARKING_STOP_SPEED}),true);assert.equal(parkingSuccess({...s,speed:PARKING_STOP_SPEED+.001}),false);assert.equal(parkingSuccess({...s,speed:.079}),false);const crossed={...s,rearX:COURSE.bayWidth/2};assert.equal(lineViolation(crossed),true);assert.equal(parkingSuccess(crossed),false);
assert.equal(predictionDirection({...INITIAL_STATE,speed:0,gear:'R'}),-1);assert.equal(predictionDirection({...INITIAL_STATE,speed:0,gear:'D'}),1);assert.equal(predictionDirection({...INITIAL_STATE,speed:-.4,gear:'D'}),-1);const preds=predictStates({...INITIAL_STATE,speed:0,gear:'R',steer:0},{distance:1,samples:10});assert.ok(preds.at(-1).rearX<INITIAL_STATE.rearX);const badPreds=predictStates({...INITIAL_STATE,rearX:Infinity,rearZ:NaN,yaw:Infinity,steer:Infinity},{distance:Infinity,samples:3});assert.equal(badPreds.length,3);for(const pose of badPreds)for(const value of[pose.rearX,pose.rearZ,pose.yaw,pose.steer])assert.ok(Number.isFinite(value));
const ref=referenceTrajectory();assert.ok(ref.length>100);const end={...ref.at(-1),speed:0};assert.equal(isFullyInsideBay(end),true);assert.ok(headingErrorToBay(end)<1e-8);assert.equal(parkingSuccess(end),true);for(const pose of ref)assert.equal(lineViolation(pose),false);near(end.rearX,0,.03);near(end.rearZ,-4.30,.05);
s={...INITIAL_STATE,rearX:0,rearZ:0,yaw:0};const poly=bodyPolygon(s);near(Math.abs(poly[1].x-poly[0].x),VEHICLE.width);near(Math.abs(poly[2].z-poly[1].z),VEHICLE.length);
console.log('physics-tests: all assertions passed');