import assert from 'node:assert/strict';
import {createTrainingSession,recordTrainingSample} from './session.mjs';
import {buildReplayMarkers,buildReplayModel,nearestReplayPoint,replayProgress,replayPoseAtProgress,replayMarkerProgress,buildReplayTimeline,createReplayPlayback,seekReplay,setReplayRate,setReplayPlaying,advanceReplay} from './replay.mjs';

const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<=e,`expected ${b}, got ${a}`);
const s=createTrainingSession({gear:'R'},0);
const sample=(t,x,{touch=false,steer=.2,gear='R',lat=0,heading=0,speed=-.4,success=false,yaw=0}={})=>({t,state:{rearX:x,rearZ:-x*.5,yaw,speed,steer,gear},deviation:{lateral:lat,headingErrorDeg:heading},lineTouch:touch,parkingSuccess:success});
for(let i=0;i<14;i++)recordTrainingSample(s,sample(i,i*.2,{touch:i===7,steer:i<5?.25:i<10?-.25:.25,gear:i>=11?'D':'R',lat:i===6?-.9:i*.02,heading:i===8?19:i,speed:i===9?-2:-.4,success:i===13}));
const markers=buildReplayMarkers(s,{maxMarkers:10});
assert.ok(markers.some(m=>m.type==='line-touch'&&m.index===7));assert.ok(markers.some(m=>m.type==='max-lateral'&&m.index===6));assert.ok(markers.some(m=>m.type==='max-heading'&&m.index===8));assert.ok(markers.some(m=>m.type==='max-speed'&&m.index===9));assert.ok(markers.some(m=>m.type==='completion'&&m.index===13));assert.ok(markers.every(m=>typeof m.label==='string'&&m.label.length));
const tiny=buildReplayModel(s,{maxPoints:3,maxMarkers:8});for(const marker of tiny.markers)assert.ok(tiny.trajectory.some(p=>p.index===marker.index),`marker ${marker.type} pose must survive`);assert.deepEqual(tiny.trajectory.map(p=>p.index),[...tiny.trajectory.map(p=>p.index)].sort((a,b)=>a-b));assert.equal(tiny.durationSec,13);
const nearest=nearestReplayPoint(tiny,1.2,-.6);assert.ok(nearest);assert.ok(nearest.distance<.01);assert.equal(nearest.index,6);assert.equal(replayProgress(tiny,0),0);assert.equal(replayProgress(tiny,13),1);assert.equal(replayProgress({trajectory:[]},4),0);
const mid=replayPoseAtProgress(tiny,.5);near(mid.t,6.5);near(mid.rearX,1.3);near(mid.rearZ,-.65);near(mid.progress,.5);near(replayPoseAtProgress(tiny,-1).t,0);near(replayPoseAtProgress(tiny,2).t,13);assert.equal(replayPoseAtProgress({trajectory:[]},.5),null);
const touch=tiny.markers.find(m=>m.type==='line-touch');near(replayMarkerProgress(tiny,touch),7/13);near(replayMarkerProgress({trajectory:[]},touch),0);
const timeline=buildReplayTimeline(tiny);assert.equal(timeline.durationSec,13);near(timeline.markers.find(m=>m.type==='line-touch').progress,7/13);assert.equal(buildReplayTimeline(null).durationSec,0);
const wrap={trajectory:[{t:0,index:0,rearX:0,rearZ:0,yaw:Math.PI-0.1,speed:0,steer:0,gear:'R'},{t:2,index:1,rearX:2,rearZ:0,yaw:-Math.PI+0.1,speed:0,steer:0,gear:'R'}]};const wrapMid=replayPoseAtProgress(wrap,.5);assert.ok(Math.abs(Math.abs(wrapMid.yaw)-Math.PI)<1e-8,'yaw interpolation must take shortest arc');
const uneven={trajectory:[{t:0,index:0,rearX:0,rearZ:0,yaw:0,speed:0,steer:0,gear:'R'},{t:.1,index:1,rearX:1,rearZ:0,yaw:0,speed:0,steer:0,gear:'R'},{t:10,index:2,rearX:2,rearZ:0,yaw:0,speed:0,steer:0,gear:'R'}]};near(replayPoseAtProgress(uneven,.5).rearX,1+(4.9/9.9));
let play=createReplayPlayback({progress:-2,rate:99,playing:true});near(play.progress,0);near(play.rate,4);assert.equal(play.playing,true);play=setReplayRate(play,2);near(play.rate,2);play=seekReplay(play,.25);near(play.progress,.25);play=setReplayPlaying(play,true);play=advanceReplay(play,{durationSec:10},1);near(play.progress,.3);assert.equal(play.playing,true);play=advanceReplay(play,{durationSec:10},100);near(play.progress,.35);assert.equal(play.playing,true);play=seekReplay(play,.99);play=advanceReplay(play,{durationSec:10},.25);near(play.progress,1);assert.equal(play.playing,false);assert.equal(setReplayPlaying(play,true).playing,false);near(advanceReplay(createReplayPlayback({playing:true}),{durationSec:0},1).progress,0);
assert.deepEqual(buildReplayMarkers(createTrainingSession(),{}),[]);console.log('replay-tests: all assertions passed');
