import assert from 'node:assert/strict';
import {createTrainingSession,recordTrainingSample,summarizeTrainingSession,scoreTrainingMetrics,extractTrainingEvents,buildReplayTrajectory,completedParkingSample,PARKING_COMPLETION_DWELL_SEC,SPEED_FREE_KMH} from './session.mjs';
import {bayClearances} from './physics.mjs';
import {enterReplayMode,exitReplayMode,resetReplayRuntime} from './replay-runtime.mjs';

resetReplayRuntime();
let s=createTrainingSession({rearX:0,rearZ:0,gear:'R'},0);recordTrainingSample(s,{t:0,state:{rearX:0,rearZ:0,speed:-.4,steer:.2,gear:'R'},deviation:{lateral:.1,headingErrorDeg:2}});recordTrainingSample(s,{t:1,state:{rearX:0,rearZ:-.4,speed:0,steer:.2,gear:'R'},deviation:{lateral:.12,headingErrorDeg:3},parkingSuccess:true});assert.equal(s.completed,false,'one zero-speed success frame must not complete an attempt');for(const t of[1.15,1.30,1.36])recordTrainingSample(s,{t,state:{rearX:0,rearZ:-.4,speed:0,steer:.2,gear:'R'},deviation:{lateral:.12,headingErrorDeg:3},parkingSuccess:true});let r=summarizeTrainingSession(s);assert.equal(r.completed,true);assert.equal(r.lineTouchEvents,0);assert.ok(r.score>=90);assert.ok(r.distanceM>.39&&r.distanceM<.41);assert.equal(r.penalties.incomplete,0);assert.equal(r.events.completion.index,4);
const base=(t,x,touch=false,steer=.2,gear='R',lat=.8,heading=18,speed=-1.8)=>({t,state:{rearX:x,rearZ:0,speed,steer,gear},deviation:{lateral:lat,headingErrorDeg:heading},lineTouch:touch});
s=createTrainingSession({gear:'R'},0);recordTrainingSample(s,base(0,0,false,.2));recordTrainingSample(s,base(1,.3,true,.2));recordTrainingSample(s,base(2,.6,true,-.2));recordTrainingSample(s,base(3,.9,false,-.2));recordTrainingSample(s,base(4,1.2,true,.2));r=summarizeTrainingSession(s);assert.equal(r.lineTouchEvents,2,'continuous contact must count as one event');assert.equal(r.steeringDirectionChanges,2);assert.equal(r.completed,false);assert.ok(r.score<60);assert.ok(r.advice.length>=3);assert.equal(r.penalties.lineTouch,50);assert.equal(r.penalties.incomplete,12);assert.ok(r.totalPenalty>50);assert.equal(r.events.firstLineTouch.index,1);assert.deepEqual(r.events.steeringChanges.map(e=>e.index),[2,4]);
s=createTrainingSession({gear:'R'},0);recordTrainingSample(s,{t:0,state:{gear:'R'}});recordTrainingSample(s,{t:1,state:{gear:'D'}});recordTrainingSample(s,{t:2,state:{gear:'R'}});r=summarizeTrainingSession(s);assert.equal(r.gearChanges,2);assert.deepEqual(r.events.gearChanges.map(e=>e.index),[1,2]);
const scored=scoreTrainingMetrics({lineTouchEvents:0,maxLateralM:.18,maxHeadingErrorDeg:5,maxSpeedKmh:SPEED_FREE_KMH,steeringDirectionChanges:5,completed:true});assert.equal(scored.score,100);assert.equal(scored.totalPenalty,0);assert.deepEqual(scored.penalties,{lineTouch:0,lateral:0,heading:0,speed:0,steering:0,incomplete:0});
s=createTrainingSession({gear:'R'},0);for(let i=0;i<12;i++)recordTrainingSample(s,base(i,i*.1,i===7,i<5?.25:-.2,i===9?'D':'R',i===6?-.95:i*.03,i===8?-22:i, i===10?-2.1:-.4));const events=extractTrainingEvents(s);assert.equal(events.maxLateral.index,6);assert.equal(events.maxLateral.value,-.95);assert.equal(events.maxHeading.index,8);assert.equal(events.maxHeading.value,-22);assert.equal(events.maxSpeed.index,10);assert.ok(Math.abs(events.maxSpeed.value-7.56)<1e-9);assert.equal(events.firstLineTouch.index,7);assert.equal(events.gearChanges[0].index,9);
const replay=buildReplayTrajectory(s,{maxPoints:9});assert.ok(replay.length<=9);assert.equal(replay[0].index,0);assert.equal(replay.at(-1).index,11);for(const idx of [6,7,8,10])assert.ok(replay.some(p=>p.index===idx),`critical index ${idx} should survive replay downsampling`);assert.deepEqual(buildReplayTrajectory(createTrainingSession(),{maxPoints:10}),[]);assert.equal(buildReplayTrajectory(s,{maxPoints:0}).length,0);

s=createTrainingSession({gear:'R'},0);const completedPose={rearX:0,rearZ:-4.15,yaw:Math.PI,speed:0,steer:0,gear:'R'},afterCompletionPose={rearX:.9,rearZ:-5.1,yaw:Math.PI,speed:.3,steer:0,gear:'D'};recordTrainingSample(s,{t:0,state:{rearX:0,rearZ:-3.7,yaw:Math.PI,speed:-.2,steer:0,gear:'R'}});for(const t of[1,1.15,1.30,1.36])recordTrainingSample(s,{t,state:completedPose,parkingSuccess:true});recordTrainingSample(s,{t:2,state:afterCompletionPose});assert.equal(completedParkingSample(s).rearZ,completedPose.rearZ);r=summarizeTrainingSession(s);assert.deepEqual(r.finalClearances,bayClearances(completedPose));assert.notDeepEqual(r.finalClearances,bayClearances(afterCompletionPose));

// A transient valid parking frame must not complete the attempt. The dwell timer
// resets as soon as the vehicle leaves the valid stopped pose.
s=createTrainingSession({gear:'R'},0);recordTrainingSample(s,{t:1,state:completedPose,parkingSuccess:true});recordTrainingSample(s,{t:1.2,state:{...completedPose,speed:.1},parkingSuccess:false});recordTrainingSample(s,{t:2,state:completedPose,parkingSuccess:true});recordTrainingSample(s,{t:2.2,state:completedPose,parkingSuccess:true});assert.equal(s.completed,false);recordTrainingSample(s,{t:2+PARKING_COMPLETION_DWELL_SEC,state:completedPose,parkingSuccess:true});assert.equal(s.completed,true);

// Sampling starts after the attempt starts. Duration must remain relative to the
// session clock, and distance must include movement before the first sample.
s=createTrainingSession({rearX:0,rearZ:0,gear:'R'},0);recordTrainingSample(s,{t:.5,state:{rearX:0,rearZ:-.2,gear:'R'}});recordTrainingSample(s,{t:1.5,state:{rearX:0,rearZ:-.6,gear:'R'}});r=summarizeTrainingSession(s);assert.equal(r.durationSec,1.5);assert.ok(Math.abs(r.distanceM-.6)<1e-9);

// Replay inspection time is not training time. A five-second review gap between
// raw timestamps 1s and 7s must produce a normalized 2s training timestamp.
resetReplayRuntime();s=createTrainingSession({rearX:0,rearZ:0,gear:'R'},0);recordTrainingSample(s,{t:1,state:{rearX:0,rearZ:0,gear:'R'}});enterReplayMode(1000);recordTrainingSample(s,{t:4,state:{rearX:9,rearZ:9,gear:'D'},lineTouch:true});assert.equal(s.samples.length,1,'samples must be ignored while replay is active');exitReplayMode({atMs:6000});recordTrainingSample(s,{t:7,state:{rearX:.2,rearZ:0,gear:'R'}});assert.equal(s.samples.at(-1).t,2);assert.equal(s.elapsedSec,2);r=summarizeTrainingSession(s);assert.equal(r.durationSec,2,'summary duration must include the pre-first-sample training interval but exclude replay pause');assert.equal(r.lineTouchEvents,0,'replay pose must not create live touch events');
resetReplayRuntime();
r=summarizeTrainingSession(createTrainingSession());assert.equal(r.score,0);assert.equal(r.grade,'未开始');assert.equal(r.events.maxLateral,null);console.log('session-tests: all assertions passed');