import assert from 'node:assert/strict';
import {createTrainingSession,recordTrainingSample,summarizeTrainingSession,scoreTrainingMetrics,extractTrainingEvents,buildReplayTrajectory} from './session.mjs';
let s=createTrainingSession({gear:'R'},0);recordTrainingSample(s,{t:0,state:{rearX:0,rearZ:0,speed:-.4,steer:.2,gear:'R'},deviation:{lateral:.1,headingErrorDeg:2}});recordTrainingSample(s,{t:1,state:{rearX:0,rearZ:-.4,speed:-.4,steer:.2,gear:'R'},deviation:{lateral:.12,headingErrorDeg:3},parkingSuccess:true});let r=summarizeTrainingSession(s);assert.equal(r.completed,true);assert.equal(r.lineTouchEvents,0);assert.ok(r.score>=90);assert.ok(r.distanceM>.39&&r.distanceM<.41);assert.equal(r.penalties.incomplete,0);assert.equal(r.events.completion.index,1);
s=createTrainingSession({gear:'R'},0);const base=(t,x,touch=false,steer=.2,gear='R',lat=.8,heading=18,speed=-1.8)=>({t,state:{rearX:x,rearZ:0,speed,steer,gear},deviation:{lateral:lat,headingErrorDeg:heading},lineTouch:touch});recordTrainingSample(s,base(0,0,false,.2));recordTrainingSample(s,base(1,.3,true,.2));recordTrainingSample(s,base(2,.6,true,-.2));recordTrainingSample(s,base(3,.9,false,-.2));recordTrainingSample(s,base(4,1.2,true,.2));r=summarizeTrainingSession(s);assert.equal(r.lineTouchEvents,2,'continuous contact must count as one event');assert.equal(r.steeringDirectionChanges,2);assert.equal(r.completed,false);assert.ok(r.score<60);assert.ok(r.advice.length>=3);assert.equal(r.penalties.lineTouch,50);assert.equal(r.penalties.incomplete,12);assert.ok(r.totalPenalty>50);assert.equal(r.events.firstLineTouch.index,1);assert.deepEqual(r.events.steeringChanges.map(e=>e.index),[2,4]);
s=createTrainingSession({gear:'R'},0);recordTrainingSample(s,{t:0,state:{gear:'R'}});recordTrainingSample(s,{t:1,state:{gear:'D'}});recordTrainingSample(s,{t:2,state:{gear:'R'}});r=summarizeTrainingSession(s);assert.equal(r.gearChanges,2);assert.deepEqual(r.events.gearChanges.map(e=>e.index),[1,2]);
const scored=scoreTrainingMetrics({lineTouchEvents:0,maxLateralM:.18,maxHeadingErrorDeg:5,maxSpeedKmh:4.5,steeringDirectionChanges:5,completed:true});assert.equal(scored.score,100);assert.equal(scored.totalPenalty,0);assert.deepEqual(scored.penalties,{lineTouch:0,lateral:0,heading:0,speed:0,steering:0,incomplete:0});
s=createTrainingSession({gear:'R'},0);for(let i=0;i<12;i++)recordTrainingSample(s,base(i,i*.1,i===7,i<5?.25:-.2,i===9?'D':'R',i===6?-.95:i*.03,i===8?-22:i, i===10?-2.1:-.4));const events=extractTrainingEvents(s);assert.equal(events.maxLateral.index,6);assert.equal(events.maxLateral.value,-.95);assert.equal(events.maxHeading.index,8);assert.equal(events.maxHeading.value,-22);assert.equal(events.maxSpeed.index,10);assert.ok(Math.abs(events.maxSpeed.value-7.56)<1e-9);assert.equal(events.firstLineTouch.index,7);assert.equal(events.gearChanges[0].index,9);
const replay=buildReplayTrajectory(s,{maxPoints:9});assert.ok(replay.length<=9);assert.equal(replay[0].index,0);assert.equal(replay.at(-1).index,11);for(const idx of [6,7,8,10])assert.ok(replay.some(p=>p.index===idx),`critical index ${idx} should survive replay downsampling`);assert.deepEqual(buildReplayTrajectory(createTrainingSession(),{maxPoints:10}),[]);assert.equal(buildReplayTrajectory(s,{maxPoints:0}).length,0);
r=summarizeTrainingSession(createTrainingSession());assert.equal(r.score,0);assert.equal(r.grade,'未开始');assert.equal(r.events.maxLateral,null);console.log('session-tests: all assertions passed');
